# Generated by Django 5.1.1 on 2024-11-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='numeroDeCandidatos',
            field=models.IntegerField(default=0),
        ),
    ]
