# Generated by Django 5.1.1 on 2024-11-08 19:17

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dataNascimento',
            field=models.DateField(),
        ),
    ]
