# Generated by Django 5.1.3 on 2024-11-08 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True)),
                ('arquivo', models.FileField(null=True, upload_to='curriculos/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
            ],
        ),
    ]
